version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: '13:00'
    pull-request-branch-name:
      separator: "-"
    target-branch: "test"
    open-pull-requests-limit: 10
    reviewers:
      - RasaHQ/atom-squad
    labels:
      - type:dependencies